project_id = "kbhyqypwwmkvssrcbfdb"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_nonce = true

[functions.merchant-onboarding]
verify_jwt = true

[functions.form-payment-webhook]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.process-settlements]
verify_jwt = false

[functions.settlement-webhook]
verify_jwt = false

[functions.update-settlement-account]
verify_jwt = true

[functions.currency-rates]
verify_jwt = false

[functions.payment-form-submit]
verify_jwt = false